/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package messages.generator;

import java.util.List;
import java.util.ArrayList;

import messages.generator.azure.AzureSender;
import messages.generator.aws.AWSSender;

public class App {

    private String connectionString;
    private String eventHubName;

    public String getGreeting() {
        System.out.println(this.getClass().getResource("/config/config.properties"));
        System.out.println(getClass().getClassLoader().getResource("."));
        return "Hello world.";
    }

    public static void main(String[] args) {

        App app = new App();
        System.out.println(app.getGreeting());
        int num = 4;

        AWSSender sender = new AWSSender(1);
        sender.sendMessages();

        /*List<AzureSender> senders = new ArrayList<>();

        for (int i = 0; i < num; i++) {
            AzureSender sender = new AzureSender(i + 1);
            senders.add(sender);
        }

        for (int i = 0; i < num; i++) {
            senders.get(i).start();
        }*/

    }
}
